import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { SceneHome } from './home/sceneHome'
import styles from '../styles/Home.module.css'
import { useRef } from 'react'

const Home: NextPage = ( props: any ) => {

  const ref = useRef<HTMLDivElement>(null!)

  return (
    <div className={styles.container}>
      <Head>
        <title>Parsekonlepeu - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <div className='container'>
          <div ref={ref} className={styles.containerHome}>
            <SceneHome {...props}/>
          </div>
        </div>

      </main>
    </div>
  )
}

export default Home
