import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Parsekonlepeu - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <div className='container'>

        </div>

      </main>

      <footer className={styles.footer}>
        <div className={styles.arrondiBasGauche}/>
        <div className={styles.arrondiBasDroit}/>
      </footer>
    </div>
  )
}

export default Home
