import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Competence.module.css'

const Conpetence: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Competences</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <div className='container'>

        </div>

      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}

export default Conpetence